<?php
$data = array (
  'typeid' => 
  array (
    'id' => '2',
    'modelid' => '1',
    'type' => 'typeid',
    'status' => '0',
    'issystem' => '1',
    'field' => 'typeid',
    'name' => '类别',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '1',
    'listorder' => '0',
    'site' => '1',
  ),
  'updatetime' => 
  array (
    'id' => '6',
    'modelid' => '1',
    'type' => 'datetime',
    'status' => '2',
    'issystem' => '1',
    'field' => 'updatetime',
    'name' => '更新时间',
    'tips' => '',
    'setting' => 'array (
  \'defaultvalue\' => \'Y-m-d H:i:s\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
    'defaultvalue' => 'Y-m-d H:i:s',
  ),
  'url' => 
  array (
    'id' => '9',
    'modelid' => '1',
    'type' => 'text',
    'status' => '2',
    'issystem' => '1',
    'field' => 'url',
    'name' => 'URL',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'status' => 
  array (
    'id' => '11',
    'modelid' => '1',
    'type' => 'box',
    'status' => '0',
    'issystem' => '1',
    'field' => 'status',
    'name' => '状态',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'username' => 
  array (
    'id' => '12',
    'modelid' => '1',
    'type' => 'text',
    'status' => '2',
    'issystem' => '1',
    'field' => 'username',
    'name' => '用户名',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'relation' => 
  array (
    'id' => '16',
    'modelid' => '1',
    'type' => 'relation',
    'status' => '0',
    'issystem' => '0',
    'field' => 'relation',
    'name' => '相关文章',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'groupids_view' => 
  array (
    'id' => '18',
    'modelid' => '1',
    'type' => 'groupid',
    'status' => '0',
    'issystem' => '0',
    'field' => 'groupids_view',
    'name' => '阅读权限',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'template' => 
  array (
    'id' => '19',
    'modelid' => '1',
    'type' => 'template',
    'status' => '2',
    'issystem' => '0',
    'field' => 'template',
    'name' => '内容页模板',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'readtime' => 
  array (
    'id' => '75',
    'modelid' => '1',
    'type' => 'datetime',
    'status' => '2',
    'issystem' => '1',
    'field' => 'readtime',
    'name' => '最后阅读',
    'tips' => '',
    'setting' => 'array (
  \'defaultvalue\' => \'Y-m-d H:i:s\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '1',
    'listorder' => '0',
    'site' => '1',
    'defaultvalue' => 'Y-m-d H:i:s',
  ),
  'reply' => 
  array (
    'id' => '81',
    'modelid' => '1',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'reply',
    'name' => '回复数',
    'tips' => NULL,
    'setting' => 'array (
  \'defaultvalue\' => \'0\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
    'defaultvalue' => '0',
  ),
  'subtitle' => 
  array (
    'id' => '111',
    'modelid' => '1',
    'type' => 'text',
    'status' => '0',
    'issystem' => '1',
    'field' => 'subtitle',
    'name' => '副标题',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'replytime' => 
  array (
    'id' => '112',
    'modelid' => '1',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'replytime',
    'name' => '最后回复时间',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'replyuid' => 
  array (
    'id' => '113',
    'modelid' => '1',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'replyuid',
    'name' => '最后回复会员ID',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'replyname' => 
  array (
    'id' => '114',
    'modelid' => '1',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'replyname',
    'name' => '最后回复会员名',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'subcontent' => 
  array (
    'id' => '115',
    'modelid' => '1',
    'type' => 'textarea',
    'status' => '0',
    'issystem' => '0',
    'field' => 'subcontent',
    'name' => '副内容',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'catid' => 
  array (
    'id' => '1',
    'modelid' => '1',
    'type' => 'catid',
    'status' => '2',
    'issystem' => '1',
    'field' => 'catid',
    'name' => '栏目',
    'tips' => '请选择栏目',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '1',
    'site' => '1',
  ),
  'title' => 
  array (
    'id' => '3',
    'modelid' => '1',
    'type' => 'title',
    'status' => '2',
    'issystem' => '1',
    'field' => 'title',
    'name' => '标题',
    'tips' => '请输入标题',
    'setting' => NULL,
    'minlength' => '1',
    'maxlength' => '100',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '2',
    'site' => '1',
  ),
  'keywords' => 
  array (
    'id' => '4',
    'modelid' => '1',
    'type' => 'keyword',
    'status' => '0',
    'issystem' => '1',
    'field' => 'keywords',
    'name' => '关键词',
    'tips' => '多关键词之间用空格或者“,”隔开',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '200',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '3',
    'site' => '1',
  ),
  'description' => 
  array (
    'id' => '5',
    'modelid' => '1',
    'type' => 'textarea',
    'status' => '0',
    'issystem' => '1',
    'field' => 'description',
    'name' => '摘要',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '200',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '4',
    'site' => '1',
  ),
  'inputtime' => 
  array (
    'id' => '14',
    'modelid' => '1',
    'type' => 'datetime',
    'status' => '2',
    'issystem' => '1',
    'field' => 'inputtime',
    'name' => '发布时间',
    'tips' => '',
    'setting' => 'array (
  \'defaultvalue\' => \'Y-m-d H:i:s\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '5',
    'site' => '1',
    'defaultvalue' => 'Y-m-d H:i:s',
  ),
  'content' => 
  array (
    'id' => '7',
    'modelid' => '1',
    'type' => 'textarea',
    'status' => '0',
    'issystem' => '0',
    'field' => 'content',
    'name' => '内容',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '6',
    'site' => '1',
  ),
  'pages' => 
  array (
    'id' => '17',
    'modelid' => '1',
    'type' => 'pages',
    'status' => '0',
    'issystem' => '0',
    'field' => 'pages',
    'name' => '分页字数',
    'tips' => '留空或者填“0”则默认1000字',
    'setting' => 'array (
  \'defaultvalue\' => \'1000\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '7',
    'site' => '1',
    'defaultvalue' => '1000',
  ),
  'thumb' => 
  array (
    'id' => '8',
    'modelid' => '1',
    'type' => 'image',
    'status' => '0',
    'issystem' => '1',
    'field' => 'thumb',
    'name' => '缩略图',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '8',
    'site' => '1',
  ),
  'downfile' => 
  array (
    'id' => '21',
    'modelid' => '1',
    'type' => 'downfile',
    'status' => '0',
    'issystem' => '0',
    'field' => 'downfile',
    'name' => '文件上传',
    'tips' => '',
    'setting' => 'array (
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'\',
  \'enablehtml\' => \'\',
  \'options\' => \'\',
  \'boxtype\' => \'\',
  \'outputtype\' => \'\',
  \'minnumber\' => \'0\',
  \'maxnumber\' => \'0\',
  \'decimaldigits\' => \'\',
  \'format\' => \'\',
  \'upload_allowext\' => \'jpg\',
  \'upload_number\' => \'\',
  \'downloadtype\' => \'1\',
  \'pathlist\' => \'0\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '9',
    'site' => '1',
    'defaultvalue' => '',
    'ispassword' => '',
    'enablehtml' => '',
    'options' => '',
    'boxtype' => '',
    'outputtype' => '',
    'minnumber' => '0',
    'maxnumber' => '0',
    'decimaldigits' => '',
    'format' => '',
    'upload_allowext' => 'jpg',
    'upload_number' => '',
    'downloadtype' => '1',
    'pathlist' => '0',
  ),
  'listorder' => 
  array (
    'id' => '10',
    'modelid' => '1',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'listorder',
    'name' => '排序',
    'tips' => '',
    'setting' => 'array (
  \'defaultvalue\' => \'0\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '10',
    'site' => '1',
    'defaultvalue' => '0',
  ),
  'read' => 
  array (
    'id' => '78',
    'modelid' => '1',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'read',
    'name' => '点击数',
    'tips' => '',
    'setting' => 'array (
  \'defaultvalue\' => \'0\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '11',
    'site' => '1',
    'defaultvalue' => '0',
  ),
  'islink' => 
  array (
    'id' => '13',
    'modelid' => '1',
    'type' => 'islink',
    'status' => '0',
    'issystem' => '1',
    'field' => 'islink',
    'name' => '转向链接',
    'tips' => '输入则访问该内容自动转跳改此链接',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '12',
    'site' => '1',
  ),
  'allow_comment' => 
  array (
    'id' => '20',
    'modelid' => '1',
    'type' => 'box',
    'status' => '0',
    'issystem' => '0',
    'field' => 'allow_comment',
    'name' => '允许评论',
    'tips' => '',
    'setting' => 'array (
  \'options\' => \'允许评论|1\\r\\n不允许评论|0\',
  \'defaultvalue\' => \'1\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '13',
    'site' => '1',
    'options' => '允许评论|1\\r\\n不允许评论|0',
    'defaultvalue' => '1',
  ),
  'readpoint' => 
  array (
    'id' => '15',
    'modelid' => '1',
    'type' => 'readpoint',
    'status' => '0',
    'issystem' => '0',
    'field' => 'readpoint',
    'name' => '阅读收费',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '14',
    'site' => '1',
  ),
);
?>