<?php
$data = array (
  'typeid' => 
  array (
    'id' => '127',
    'modelid' => '4',
    'type' => 'typeid',
    'status' => '0',
    'issystem' => '1',
    'field' => 'typeid',
    'name' => '类别',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '1',
    'listorder' => '0',
    'site' => '1',
  ),
  'readtime' => 
  array (
    'id' => '131',
    'modelid' => '4',
    'type' => 'datetime',
    'status' => '2',
    'issystem' => '1',
    'field' => 'readtime',
    'name' => '最后阅读',
    'tips' => NULL,
    'setting' => 'array (
  \'defaultvalue\' => \'Y-m-d H:i:s\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '1',
    'listorder' => '0',
    'site' => '1',
    'defaultvalue' => 'Y-m-d H:i:s',
  ),
  'updatetime' => 
  array (
    'id' => '132',
    'modelid' => '4',
    'type' => 'datetime',
    'status' => '2',
    'issystem' => '1',
    'field' => 'updatetime',
    'name' => '更新时间',
    'tips' => NULL,
    'setting' => 'array (
  \'defaultvalue\' => \'Y-m-d H:i:s\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
    'defaultvalue' => 'Y-m-d H:i:s',
  ),
  'url' => 
  array (
    'id' => '135',
    'modelid' => '4',
    'type' => 'text',
    'status' => '2',
    'issystem' => '1',
    'field' => 'url',
    'name' => 'URL',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'reply' => 
  array (
    'id' => '138',
    'modelid' => '4',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'reply',
    'name' => '回复数',
    'tips' => NULL,
    'setting' => 'array (
  \'defaultvalue\' => \'0\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
    'defaultvalue' => '0',
  ),
  'status' => 
  array (
    'id' => '139',
    'modelid' => '4',
    'type' => 'box',
    'status' => '0',
    'issystem' => '1',
    'field' => 'status',
    'name' => '状态',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'username' => 
  array (
    'id' => '140',
    'modelid' => '4',
    'type' => 'text',
    'status' => '2',
    'issystem' => '1',
    'field' => 'username',
    'name' => '用户名',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'relation' => 
  array (
    'id' => '144',
    'modelid' => '4',
    'type' => 'relation',
    'status' => '0',
    'issystem' => '0',
    'field' => 'relation',
    'name' => '相关文章',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'groupids_view' => 
  array (
    'id' => '146',
    'modelid' => '4',
    'type' => 'groupid',
    'status' => '0',
    'issystem' => '0',
    'field' => 'groupids_view',
    'name' => '阅读权限',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '1',
    'listorder' => '0',
    'site' => '0',
  ),
  'template' => 
  array (
    'id' => '147',
    'modelid' => '4',
    'type' => 'template',
    'status' => '2',
    'issystem' => '0',
    'field' => 'template',
    'name' => '内容页模板',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'replytime' => 
  array (
    'id' => '151',
    'modelid' => '4',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'replytime',
    'name' => '最后回复时间',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'replyuid' => 
  array (
    'id' => '152',
    'modelid' => '4',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'replyuid',
    'name' => '最后回复会员ID',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'replyname' => 
  array (
    'id' => '153',
    'modelid' => '4',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'replyname',
    'name' => '最后回复会员名',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'subcontent' => 
  array (
    'id' => '154',
    'modelid' => '4',
    'type' => 'textarea',
    'status' => '0',
    'issystem' => '0',
    'field' => 'subcontent',
    'name' => '副内容',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '1',
    'isadd' => '0',
    'listorder' => '0',
    'site' => '1',
  ),
  'catid' => 
  array (
    'id' => '126',
    'modelid' => '4',
    'type' => 'catid',
    'status' => '2',
    'issystem' => '1',
    'field' => 'catid',
    'name' => '栏目',
    'tips' => '请选择栏目',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '1',
    'site' => '1',
  ),
  'title' => 
  array (
    'id' => '128',
    'modelid' => '4',
    'type' => 'title',
    'status' => '2',
    'issystem' => '1',
    'field' => 'title',
    'name' => '标题',
    'tips' => '请输入标题',
    'setting' => NULL,
    'minlength' => '1',
    'maxlength' => '100',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '2',
    'site' => '1',
  ),
  'subtitle' => 
  array (
    'id' => '150',
    'modelid' => '4',
    'type' => 'text',
    'status' => '0',
    'issystem' => '1',
    'field' => 'subtitle',
    'name' => '副标题',
    'tips' => '使用空格分隔',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '2',
    'site' => '1',
  ),
  'keywords' => 
  array (
    'id' => '129',
    'modelid' => '4',
    'type' => 'keyword',
    'status' => '0',
    'issystem' => '1',
    'field' => 'keywords',
    'name' => '关键词',
    'tips' => '多关键词之间用空格或者“,”隔开',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '200',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '3',
    'site' => '1',
  ),
  'description' => 
  array (
    'id' => '130',
    'modelid' => '4',
    'type' => 'textarea',
    'status' => '0',
    'issystem' => '1',
    'field' => 'description',
    'name' => '摘要',
    'tips' => '',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '200',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '4',
    'site' => '1',
  ),
  'inputtime' => 
  array (
    'id' => '142',
    'modelid' => '4',
    'type' => 'datetime',
    'status' => '2',
    'issystem' => '1',
    'field' => 'inputtime',
    'name' => '发布时间',
    'tips' => NULL,
    'setting' => 'array (
  \'defaultvalue\' => \'Y-m-d H:i:s\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '5',
    'site' => '1',
    'defaultvalue' => 'Y-m-d H:i:s',
  ),
  'content' => 
  array (
    'id' => '133',
    'modelid' => '4',
    'type' => 'textarea',
    'status' => '0',
    'issystem' => '0',
    'field' => 'content',
    'name' => '内容',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '6',
    'site' => '1',
  ),
  'pages' => 
  array (
    'id' => '145',
    'modelid' => '4',
    'type' => 'pages',
    'status' => '0',
    'issystem' => '0',
    'field' => 'pages',
    'name' => '分页字数',
    'tips' => '留空或者填“0”则默认1000字',
    'setting' => 'array (
  \'defaultvalue\' => \'1000\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '7',
    'site' => '1',
    'defaultvalue' => '1000',
  ),
  'thumb' => 
  array (
    'id' => '134',
    'modelid' => '4',
    'type' => 'image',
    'status' => '0',
    'issystem' => '1',
    'field' => 'thumb',
    'name' => '缩略图',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '8',
    'site' => '1',
  ),
  'downfile' => 
  array (
    'id' => '149',
    'modelid' => '4',
    'type' => 'downfile',
    'status' => '0',
    'issystem' => '0',
    'field' => 'downfile',
    'name' => '文件上传',
    'tips' => NULL,
    'setting' => 'array (
  \'defaultfile\' => \'3\',
  \'maxfile\' => \'10\',
  \'options\' => \'直接下载|1\\r\\n跳转下载|0\',
  \'defaultvalue\' => \'1\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '1',
    'listorder' => '9',
    'site' => '1',
    'defaultfile' => '3',
    'maxfile' => '10',
    'options' => '直接下载|1\\r\\n跳转下载|0',
    'defaultvalue' => '1',
  ),
  'listorder' => 
  array (
    'id' => '136',
    'modelid' => '4',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'listorder',
    'name' => '排序',
    'tips' => NULL,
    'setting' => 'array (
  \'defaultvalue\' => \'0\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '10',
    'site' => '1',
    'defaultvalue' => '0',
  ),
  'read' => 
  array (
    'id' => '137',
    'modelid' => '4',
    'type' => 'number',
    'status' => '2',
    'issystem' => '1',
    'field' => 'read',
    'name' => '点击数',
    'tips' => NULL,
    'setting' => 'array (
  \'defaultvalue\' => \'0\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '11',
    'site' => '1',
    'defaultvalue' => '0',
  ),
  'islink' => 
  array (
    'id' => '141',
    'modelid' => '4',
    'type' => 'islink',
    'status' => '0',
    'issystem' => '1',
    'field' => 'islink',
    'name' => '转向链接',
    'tips' => '输入则访问该内容自动转跳改此链接',
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '12',
    'site' => '1',
  ),
  'allow_comment' => 
  array (
    'id' => '148',
    'modelid' => '4',
    'type' => 'box',
    'status' => '0',
    'issystem' => '0',
    'field' => 'allow_comment',
    'name' => '允许评论',
    'tips' => NULL,
    'setting' => 'array (
  \'options\' => \'允许评论|1\\r\\n不允许评论|0\',
  \'defaultvalue\' => \'1\',
)',
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '13',
    'site' => '1',
    'options' => '允许评论|1\\r\\n不允许评论|0',
    'defaultvalue' => '1',
  ),
  'readpoint' => 
  array (
    'id' => '143',
    'modelid' => '4',
    'type' => 'readpoint',
    'status' => '0',
    'issystem' => '0',
    'field' => 'readpoint',
    'name' => '阅读收费',
    'tips' => NULL,
    'setting' => NULL,
    'minlength' => '0',
    'maxlength' => '0',
    'del' => '1',
    'hide' => '0',
    'isadd' => '0',
    'listorder' => '14',
    'site' => '1',
  ),
);
?>