<?php
$data = array (
  1 => 
  array (
    'id' => '1',
    'type' => 'new',
    'type_cn' => '默认类型',
    'title' => '文章模型',
    'body' => '',
    'tablename' => 'news',
    'mode' => '0',
    'num' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'addtime' => '1382072744',
    'site' => '1',
  ),
  2 => 
  array (
    'id' => '2',
    'type' => 'new',
    'type_cn' => '默认类型',
    'title' => '下载模型',
    'body' => '',
    'tablename' => 'download',
    'mode' => '0',
    'num' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list_xiazai',
    'show_template' => 'show_xiazai',
    'addtime' => '1382079361',
    'site' => '1',
  ),
  3 => 
  array (
    'id' => '3',
    'type' => 'new',
    'type_cn' => '默认类型',
    'title' => '图片模型',
    'body' => '',
    'tablename' => 'picture',
    'mode' => '0',
    'num' => '0',
    'default_style' => 'default',
    'category_template' => 'category_tupian',
    'list_template' => 'list_tupian',
    'show_template' => 'show_tupian',
    'addtime' => '1382079385',
    'site' => '1',
  ),
  4 => 
  array (
    'id' => '4',
    'type' => 'bbs',
    'type_cn' => '论坛类型',
    'title' => '论坛模型',
    'body' => '',
    'tablename' => 'bbs',
    'mode' => '0',
    'num' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list_bbs',
    'show_template' => 'show_bbs',
    'addtime' => '1388378448',
    'site' => '1',
  ),
);
?>